### ISSUE TITLE
Unhandled rejection Error: Command failed: termux-clipboard-set

### ISSUE THREAD

**Issue by tghirfn** [anasrar/Samehadaku-Lewatin#3]
Hello im using termux app in android,
I was installed apt-install termux-api

when the link appears, and I press ctrl + c then appear : 

Unhandled rejection Error: Command failed: termux-clipboard-set

    at makeError (/data/data/com.termux/files/usr/lib/node_modules/samehadaku-lewatin/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (/data/data/com.termux/files/usr/lib/node_modules/samehadaku-lewatin/node_modules/execa/index.js:338:15)
    at Object.copySync (/data/data/com.termux/files/usr/lib/node_modules/samehadaku-lewatin/node_modules/clipboardy/lib/termux.js:29:10)
    at Object.exports.writeSync.text [as writeSync] (/data/data/com.termux/files/usr/lib/node_modules/samehadaku-lewatin/node_modules/clipboardy/index.js:39:14)
    at Pancal.request.then (/data/data/com.termux/files/usr/lib/node_modules/samehadaku-lewatin/module/fetch.js:228:27)
    at tryCatcher (/data/data/com.termux/files/usr/lib/node_modules/samehadaku-lewatin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandle

**Comment by anasrar** [comment]
can you send me a video or gif image that you try to copy link

**Comment by anasrar** [comment]
i think the problem is from termux clipboard
you can use flag ```-s``` or ```--save``` to save link into a file txt

**Comment by anasrar** [comment]
from my android emulator is work fine

Install Termux API https://apkpure.com/termux-api/com.termux.api

In Termux

```
apt install termux-api
```

![image](https://user-images.githubusercontent.com/38805204/59550383-4362f000-8f94-11e9-8977-5aa2bc4ead48.png)

**Comment by sukebehiro** [comment]
Install Termux API on Playstore if your termux error or not support copy link on clipboard :)
